
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 986672551393.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=986672551393.dkr.ecr.us-west-2.amazonaws.com/aws-ecr-r4r-2024
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
